# Generated by Django 6.0.2 on 2026-03-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciepApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciep',
            new_name='Recipe',
        ),
    ]
